ビルドのキャンセルの実装
traPtitech/NeoShowcase pull request #231
Opened 2021-11-02 12:09 UTC by hijiki51

2021-11-03 14:01 UTC, cskd8 requested changes
とりあえず気になったとこだけ

2021-11-03 14:01 UTC, cskd8 commented on pkg/usecase/app_build_service.go
> +	return nil
どういう発火方法かにもよるけど、キャンセル連打とかされると`canceledJobList`にどんどん積まれることとかもあるかもでちょっと気になった

2021-11-03 14:02 UTC, hijiki51 commented on pkg/usecase/app_build_service.go
> +		}
あ～忘れてました。入れます

2021-11-03 14:04 UTC, hijiki51 commented on pkg/usecase/app_build_service.go
> +	return nil
追加する前に存在するかチェックするのがいいですかね？

2021-11-03 14:06 UTC, cskd8 commented on pkg/usecase/app_build_service.go
> +	return nil
それでいいと思う、削除の処理とあわせていい感じにやってくれると:tasukaru:

2021-11-04 03:24 UTC, hijiki51 commented
修正しました

2021-11-06 15:16 UTC, FujishigeTemma commented on pkg/usecase/app_build_service.go
> +func (s *appBuildService) CancelBuild(ctx context.Context, jobID JobID) error {
クライアントには`build_logs`が返ってるはずで、その中から終わってないやつをキャンセルすることになると思う。
現状、`'BUILDING','SUCCEEDED','FAILED','CANCELED'`のenumになってるけど「`build status`テーブルを別で用意してenumじゃなくする＆`'queued','skipped'`を追加する」をして欲しい。
んで、QueueBuildされたタイミングで`build_log`に入れるようにして欲しい。（あと、現状builder側で`build_log`直接触ってるけどそれは残しておいていい→今後、grpcを介するようにする）
そうしたら、JobIDを別で用意しなくて良くなると思う。
queueはchannelじゃなくてpriority queueを実装して使ってください。（今、lockをとってないからそのへんも気にしてもらえるといいかも）

2021-11-06 15:16 UTC, FujishigeTemma commented on pkg/usecase/app_build_service.go
> +func (s *appBuildService) CancelBuild(ctx context.Context, jobID JobID) error {
って考えなんだけど、実装で詰まったり、うまく行かなそうなところを見つけたりしたら相談して欲しい。

2021-11-06 15:21 UTC, FujishigeTemma commented on pkg/usecase/app_build_service.go
> +func (s *appBuildService) CancelBuild(ctx context.Context, jobID JobID) error {
enumの話は「31 flavor」とかでググると雰囲気わかると思う

2022-05-05 07:36 UTC, FujishigeTemma commented on pkg/usecase/app_build_service.go
>  			}
ここsync.Condとかで書いてみて欲しいです

2022-05-10 06:19 UTC, FujishigeTemma commented
rebaseお願いしてもいいですか:pray:

2022-05-12 16:34 UTC, FujishigeTemma requested changes

2022-05-12 16:34 UTC, FujishigeTemma commented on pkg/interface/repository/artifact.go
> +	}
エラーハンドリングするのをTODOにしておいて欲しいのと、os.Statはrepoの外で呼び出して、sizeとかを引数に取るようにして欲しい

2022-05-12 16:34 UTC, FujishigeTemma commented on pkg/usecase/app_build_service.go
> +			v := s.queue.Top()
TopよりPeekのほうが一般的な気がする？

2022-05-12 16:34 UTC, FujishigeTemma commented on pkg/usecase/app_build_service_test.go
> +		err = s.CancelBuild(context.Background(), id)
これちゃんとキャンセルされてるか確認するように欲しい
↓は助けになるかも？
https://engineering.mercari.com/blog/entry/2018-08-08-080000/

2022-05-12 16:34 UTC, FujishigeTemma commented on pkg/usecase/builder_service.go
> +	buildLogRepo repository.BuildLogRepository
後で消すはTODOのままで残しておいて欲しい

2022-05-16 06:23 UTC, FujishigeTemma commented on pkg/usecase/app_build_service_test.go
> +		require.Equal(t, len(queue.data), 0)
これ、runされてQueueから消えてても大丈夫説ない？

2022-05-16 06:25 UTC, FujishigeTemma commented on pkg/usecase/builder_service.go
> +				size := stat.Size()
これそのまま引数にとっていいよ

2022-08-20 04:58 UTC, FujishigeTemma submitted a review, later dismissed
:LGTM:
ありがとうございます！

2022-08-20 06:01 UTC, merged