add memberchecker
traPtitech/NeoShowcase pull request #3
Opened 2020-10-24 17:38 UTC by hijiki51

## Membercheckerの実装

- リクエストのCookieのext_traP_tokenを見て、部員だったら200 OKとX-Showcase-Userを返す

2020-10-25 01:20 UTC, wtks requested changes

2020-10-25 01:20 UTC, wtks commented on pkg/memberchecker/authenticator.go
> +var pubkey *rsa.PublicKey
使用する公開鍵については、 https://github.com/traPtitech/NeoShowcase/blob/391609133292df552d9a5af706af746a7f2e7e3d/pkg/memberchecker/service.go#L14
のものを使うようにしてください

2020-10-25 01:20 UTC, wtks commented on pkg/memberchecker/authenticator.go
> +func AuthorizeMemberByToken(w http.ResponseWriter, r *http.Request) {
ハンドラのロジックとしてはこれで問題ないのですが、これは標準httpライブラリのハンドラとして実装されてるので、それをechoライブラリのハンドラとして実装して欲しいです。(要するに上のauthenticate関数の中に書く)

2020-10-25 17:23 UTC, hijiki51 commented on pkg/memberchecker/authenticator.go
> +func AuthorizeMemberByToken(w http.ResponseWriter, r *http.Request) {
多分直せたと思うんですけど、デバッグの仕方がわかりません。一回generate.goを
```
/ go:generate sqlboiler mysql
// go:generate pkger -o cmd/ns-migrate
package main

import (
	"github.com/labstack/echo/v4"
	"github.com/traPtitech/neoshowcase/pkg/memberchecker"
)

func main() {

	e := echo.New()
	c := memberchecker.Config{
		HTTPPort: 55555,
	}
	s := memberchecker.Service{
		config: c,
	}

	e.GET("/", s.authenticate)
	e.Logger.Fatal(e.Start(":55555"))
}
```
のように書き換えてデバッグしてみようと思ったんですけど、
```
./generate.go:17:3: unknown field 'config' in struct literal of type memberchecker.Service
./generate.go:20:14: s.authenticate undefined (cannot refer to unexported field or method memberchecker.(*Service).authenticate)
```
というエラーが出てうまくいきませんでした。

2020-10-28 02:00 UTC, wtks commented on pkg/memberchecker/authenticator.go
> +func AuthorizeMemberByToken(w http.ResponseWriter, r *http.Request) {
ごめん見逃してた。
今の所go test環境が整ってないので、手動で動作確認することになるんですけど、サーバーの起動方法は２つあります。
1つ目はdocker上で起動する方法で、docker-compose.yamlにメンバーチェッカーのサーバーが定義されてるので、コード変更したら`docker-compose up -d --build ns-mc`としたらビルドと起動が走ります。起動したらローカルホストの5005番ポートからアクセスできます。
2つ目はgo runで起動する方法で、メンバーチェッカーのサーバーのmain.goは`cmd/ns-mc/main.go`にあるので、`go run cmd/ns-mc/main.go -p 8081`を実行したら、8081番ポートからアクセスできます。

2020-10-28 02:01 UTC, wtks commented on pkg/memberchecker/authenticator.go
> +	q := c.Request().URL.Query().Get("type")
c.QueryParamを使うともっと短く書けますよ

2020-10-28 02:08 UTC, wtks commented on pkg/memberchecker/authenticator.go
> +func AuthorizeMemberByToken(w http.ResponseWriter, r *http.Request) {
generate.goのエラーについては、
Go言語の仕様で、名前が小文字から始まる関数・メソッド・変数・フィールドは外部のパッケージからアクセスできないので、memberchecker.Serviceのconfigには代入できないし、s.authenticateメソッドは呼び出せません。

パッケージ構成とカプセル化の観点から、大文字に変更してアクセスできるようにするべきではないし、する必要もありません。

2020-11-03 16:13 UTC, hijiki51 commented on pkg/memberchecker/authenticator.go
> +func AuthorizeMemberByToken(w http.ResponseWriter, r *http.Request) {
`go run cmd/ns-mc/main.go -p 8081`のほうですが、
```
NeoShowcase MemberCheckerServer

Usage:
  ns-mc [command]

Available Commands:
  help        Help about any command
  serve

Flags:
  -h, --help                 help for ns-mc
  -p, --port int             port num (default 8081)
  -k, --pubkey-file string   public key PEM file path
  -v, --version              version for ns-mc

Use "ns-mc [command] --help" for more information about a command.
```
となってしまい。動きません。
`docker-compose up -d --build ns-mc`
のほうは、正常に起動し、レスポンスもかえってくるのですが、必要なメソッドが足りず、authenticatorのほうまで行く前に`"code=405, message=Method Not Allowed"`となってしまいます。南尾メソッドが要求されているのかいまいちわからないのですが、どうすればいいでしょうか

2020-11-03 23:54 UTC, wtks commented on pkg/memberchecker/authenticator.go
> +func AuthorizeMemberByToken(w http.ResponseWriter, r *http.Request) {
go runの方だけど`go run cmd/ns-mc/main.go serve -p 8081`こうだった。
authenticateハンドラはhttps://github.com/traPtitech/NeoShowcase/blob/16765e1d15a120591997dd01c880cea230c62700/pkg/memberchecker/service.go#L29 でHTTP GETで登録してます

2020-11-04 00:02 UTC, wtks commented on pkg/memberchecker/authenticator.go
> +func AuthorizeMemberByToken(w http.ResponseWriter, r *http.Request) {
なので、`http://localhost:5005/?type=hard`に対してtraP_ext_tokenをリクエストヘッダのクッキーに入れて、HTTP GETをしてテストしてください。
traP_ext_tokenは現行のShowcaseで発行されてる自分のものを取ってこれて、それを送ると200 OK、それを適当に弄った文字列を送ると403で通らないことが確認できるはず

2020-11-04 01:46 UTC, hijiki51 commented
うまく動いたと思うので再度チェックお願いできますか

2020-11-05 13:08 UTC, wtks approved these changes

2020-11-05 13:08 UTC, merged