#26 旧showcase.yamlイメージビルド対応
traPtitech/NeoShowcase pull request #70
Opened 2021-02-18 06:40 UTC by hijiki51

こんな感じで大丈夫でしょうか

2021-02-18 11:01 UTC, hijiki51 commented
修正しました、レビューお願いします

2021-02-18 11:05 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
ここで作ったシェルスクリプトのファイルをDockerイメージ内にADDする必要があります(イメージに入れないとRUNやENTRYPOINTで呼べない)

2021-02-18 11:10 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
これ COPY . .で入っていると思ってたんですが、入らないんですかね？

2021-02-18 11:15 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
ioutil.TempFileは/tmp以下のどこかにstartupScriptNameにランダムな文字列を付け加えた一時的なファイルを作ってて、リポジトリのあるディレクトリにファイル作ってるわけではないですね

2021-02-18 11:18 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
なるほど、把握しました

2021-02-18 11:29 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
`ADD .tmp/{filename}`みたいな形でいいですかね？

2021-02-18 11:45 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
あ、buildkitdに送られるコンテキストのディレクトリは https://github.com/traPtitech/NeoShowcase/blob/c715a4ee364b8a125963695d1b5f9eee1285c4c3/pkg/builder/task.go#L247
にあるように、リポジトリのディレクトリのみなので、シェルスクリプトはリポジトリのディレクトリ以下に入れないとダメですね。。

2021-02-18 11:45 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
そうするとCOPY . .で対応出来るのでADDいらないです

2021-02-18 11:59 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
であれば、`t.repositoryTempDir+'/'+f.Name()`で大丈夫ですかね？

2021-02-18 12:17 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
いや、ioutil.Tempfile使わずに、os.Createで`filepath.Join(t.repositoryTempDir, startupScriptName)`(t.repositoryTempDir+"/"+startupScriptName)にシェルスクリプトファイルを作る必要があります

2021-02-18 12:46 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := ioutil.TempFile("", startupScriptName)
なるほど、把握しました

2021-02-19 03:45 UTC, hijiki51 commented
修正しました、確認お願いします

2021-02-19 04:49 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.Create(fspath)
作ったシェルスクリプトファイルに実行権限つけないといけないの忘れてたので、つけといてください
`os.Create`って言っちゃったけど、権限つけるなら`os.OpenFile`の方がいいですね

2021-02-19 04:51 UTC, wtks commented on pkg/builder/task.go
> +#!/bin/sh
shebang2行目にすると動かない気がするので1行目の改行消してください

2021-02-19 04:54 UTC, wtks commented on pkg/builder/task.go
> +`, t.BuildOptions.BaseImageName, fs.Name(), fe.Name())
↑でフルパスを指定してファイル作った関係で、多分`fs.Name(), fe.Name()`はフルパスが返ってくると思うので、`startupScriptName, entryPointScriptName`ですかね

2021-02-19 13:42 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.Create(fspath)
権限は 777でいいですかね？

2021-02-19 14:38 UTC, hijiki51 commented
修正しました

2021-02-19 14:44 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.Create(fspath)
755がいいかな

2021-02-19 14:56 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.Create(fspath)
変更しました

2021-02-20 05:09 UTC, wtks requested changes
builderをリビルドした後に、evansでbuilderに接続して、
```
neoshowcase.proto.services.builder.BuilderService@localhost:5006> call StartBuildImage
image_name (TYPE_STRING) => 
source::repository_url (TYPE_STRING) => https://github.com/wtks/ns-test.git
source::ref (TYPE_STRING) => 
options::base_image_name (TYPE_STRING) => wtks/ns-base:20210110
options::entrypoint_cmd (TYPE_STRING) => /app
options::startup_cmd (TYPE_STRING) => go build -o /app .
options::artifact_path (TYPE_STRING) => 
environment_id (TYPE_STRING) => 
```
でcallすればテストできます

2021-02-20 05:09 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
os.O_RDWRだけだとファイルが作成されないので、O_RDWR|O_CREATE|O_TRUNCでお願いします

2021-02-20 17:22 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
リビルドは
https://md.trap.jp/aL-J5_bITZmc6GWOQmwxDA
にある開発サーバーでやるのでしょうか？その場合、ns-masterのリポジトリを更新すればいいのでしょうか？

2021-02-20 17:23 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
ローカルのPCでの話ですね

2021-02-21 04:05 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
すみません、evansでの接続の仕方がわかりません…

2021-02-21 04:16 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
`make ns-builder-evans`って打つか、ここに書かれてるコマンドを先頭の`@`除いて実行してください
https://github.com/traPtitech/NeoShowcase/blob/ca8f366cf6f377294ad5d49901c5adca3ea1bf26/Makefile#L58

2021-02-21 04:29 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
```
evans: failed to run REPL mode: failed to instantiate a new spec: failed to instantiate the spec: failed to list packages by gRPC reflection: failed to list services from reflecton enabled gRPC server: rpc error: code = Unavailable desc = connection closed
make: *** [Makefile:59: ns-builder-evans] Error 1
```
こんなエラーが出てしまうのですが、どうすればいいですか？

2021-02-21 04:35 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
docker-compose.yamlは起動してるよね？
なんだろう・・・

2021-02-21 04:36 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
DBが死んでましたが関係ありますかね？
```
 hijiki51  DESKTOP-JF9KJFE  ~  $  docker ps -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                            PORTS                                                   NAMES
0a26ea2b5968   neoshowcase_ns-ssgen                       "dockerize -timeout …"   7 minutes ago   Up 11 seconds                     0.0.0.0:5007->10000/tcp                                 neoshowcase_ns-ssgen_1
069f50ff51bd   swaggerapi/swagger-ui                      "/docker-entrypoint.…"   7 minutes ago   Up 7 minutes                      80/tcp, 8080/tcp                                        neoshowcase_swagger-ui_1
344ca64ce9ba   neoshowcase_ns                             "dockerize -timeout …"   7 minutes ago   Up 13 seconds                     8080/tcp                                                neoshowcase_ns_1
0eede8beebf3   neoshowcase_ns-builder                     "dockerize -timeout …"   7 minutes ago   Up 13 seconds                     0.0.0.0:5006->10000/tcp                                 neoshowcase_ns-builder_1
f4d234bd2347   moby/buildkit:latest                       "buildkitd --addr tc…"   7 minutes ago   Up 7 minutes                      0.0.0.0:5002->1234/tcp                                  neoshowcase_buildkitd_1
5dee3b7fb508   caddy:2.1.1-alpine                         "caddy run --config …"   7 minutes ago   Up 7 minutes                      443/tcp, 0.0.0.0:5008->80/tcp, 0.0.0.0:5009->2019/tcp   neoshowcase_staticsite_1
3e9f3baccc52   adminer:4.7.5                              "entrypoint.sh docke…"   7 minutes ago   Up 7 minutes                      0.0.0.0:5001->8080/tcp                                  neoshowcase_adminer_1
6053c71e5f38   mariadb:10.0.19                            "/docker-entrypoint.…"   7 minutes ago   Restarting (139) 31 seconds ago                                                           neoshowcase_mysql_1
a1fee5567f14   mongo                                      "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                      0.0.0.0:5010->27017/tcp                                 neoshowcase_mongo_1
310b08d6e3e6   traefik:v2.3                               "/entrypoint.sh --ap…"   7 minutes ago   Up 7 minutes                      0.0.0.0:8080->8080/tcp, 0.0.0.0:8888->80/tcp            neoshowcase_traefik_1
f8fd983b86e0   registry:2                                 "/entrypoint.sh /etc…"   7 minutes ago   Up 7 minutes                      0.0.0.0:5000->5000/tcp                                  neoshowcase_registry_1
6a9f5200fc11   konradkleine/docker-registry-frontend:v2   "/bin/sh -c $START_S…"   7 minutes ago   Up 7 minutes                      443/tcp, 0.0.0.0:5003->80/tcp                           neoshowcase_registry-frontend_1
b138ad1a4213   neoshowcase_ns-mc                          "/app/ns-mc serve"       7 minutes ago   Up 7 minutes                      0.0.0.0:5005->8081/tcp                                  neoshowcase_ns-mc_1
```

2021-02-21 04:37 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
あーそれですね

2021-02-21 04:38 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
mariadbのバージョンlatestにあげて大丈夫です

2021-02-21 04:38 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
いつものlatestにしないとDBがうごかないバグがここでも発生しているのですが、どこを書き換えればいいのでしょうか

2021-02-21 04:39 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
https://github.com/traPtitech/NeoShowcase/blob/ca8f366cf6f377294ad5d49901c5adca3ea1bf26/docker-compose.yaml#L148

2021-02-21 04:40 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
あと、これ多分説明するの忘れてたんですが、docker-composeでDBのコンテナが無事立ち上がったら、`make migrate-up`を実行してDBの初期化をしてください

2021-02-21 04:42 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
動きました、ありがとうございます

2021-02-21 05:08 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
たびたびすみません、buildidが返ってくるのですが、テスト結果をどう読み取ればいいのでしょうか？

2021-02-21 05:10 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
builderコンテナのログで特にエラーとか出てなかったらイケてると思います

2021-02-21 05:12 UTC, wtks commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
`level=debug msg="task finished" buildID=ycbg0i5strgdgay4nnw62w result=SUCCEEDED`みたいなの出てたら成功

2021-02-21 05:49 UTC, hijiki51 commented on pkg/builder/task.go
> +			fs, err := os.OpenFile(filepath.Join(t.repositoryTempDir, startupScriptName), os.O_RDWR, filePermission)
今度こそ大丈夫なはず…

2021-02-21 06:00 UTC, wtks approved these changes

2021-02-21 06:00 UTC, merged