feat: 🎸 pod schedulingの管理
traPtitech/NeoShowcase pull request #723
Opened 2023-09-21 12:36 UTC by hijiki51

## なぜやるか
resolve https://github.com/traPtitech/NeoShowcase/issues/720

## やったこと
XXH3Hashを利用してappIDから配置ホストを決定するようにした

## やらなかったこと

## 資料
https://q.trap.jp/messages/75d88573-25be-42d2-8e71-ce97af31ec09

2023-09-21 13:03 UTC, motoki317 commented on pkg/infrastructure/backend/k8simpl/config.go
> +		ForceHosts   []string        `mapstructure:"forceHosts" yaml:"forceHosts"`
無くても挙動は同じかもですが、設定オプションを追加したので、↓ココで一応デフォルト値を設定してもらいたいです :pray:
わかりにくいですよね...
https://github.com/traPtitech/NeoShowcase/blob/2c6cea5c3c434b14f0711d776303af6c83a01ff2/cmd/ns-controller/config.go#L81

2023-09-22 00:18 UTC, hijiki51 commented on pkg/infrastructure/backend/k8simpl/config.go
> +		ForceHosts   []string        `mapstructure:"forceHosts" yaml:"forceHosts"`
つけました（viperのDefault忘れがち）

2023-09-22 00:26 UTC, motoki317 requested changes

2023-09-22 00:26 UTC, motoki317 commented on pkg/infrastructure/backend/k8simpl/config.go
>  	}
ここは外さないとまずそうですね nodeSelectorの設定がないときに設定されなくなっちゃう
見落としてました

2023-09-22 00:26 UTC, motoki317 commented on pkg/infrastructure/backend/k8simpl/config.go
> +	nodeSelectorKey = "kubernetes.io/hostname"
こっちの名前のほうが情報量が多いかも
```suggestion
	hostnameNodeLabel = "kubernetes.io/hostname"
```

2023-09-22 01:17 UTC, motoki317 approved these changes
動かしてないけど本番で試してみてもいいかな()
タグ打ってリリース(自動)、↓から設定変更もできると思うのでもしよかったらお願いします
https://github.com/traPtitech/manifest/blob/main/ns-system/config/ns-controller.yaml

2023-09-22 02:19 UTC, merged